backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
    - name: "content"
    label: "Movies & Series"
    folder: "_content"
    create: true
    fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Thumbnail", name: "thumbnail", widget: "image"}
            - {label: "Category Kubwa", name: "category", widget: "select", options: ["series", "singo"]}
            - {label: "Genre", name: "genre", widget: "select", options: ["Action", "Love Story", "Drama", "Horror", "Comedy"]}
            - {label: "Type", name: "type", widget: "select", options: ["series", "singo"]}
            - {label: "Weka Kwenye Slide?", name: "featured", widget: "boolean", default: false}
            - {label: "Ni BURE?", name: "is_free", widget: "boolean", default: true}
            - {label: "Bei TSh", name: "price", widget: "number", default: 0, value_type: "int"}
            - {label: "Video Link", name: "video", widget: "string", required: false, hint: "Kwa Singo Movie tu"}
            - {label: "Idadi ya Episodes", name: "episodes", widget: "number", required: false, hint: "Kwa Series tu"}
            - label: "List ya Episodes"
        name: "episodeList"
        widget: "list"
        required: false
        hint: "Kwa Series tu"
        fields:
                    - {label: "Jina la Episode", name: "title", widget: "string"}
                    - {label: "Video Link", name: "video", widget: "string"}
